matrix:
  allow_failures: java
  include:
    - name: go test
      language: go
      go:
        - 1.12.x
      go_import_path: github.com/Fantom-foundation/go-lachesis
      gobuild_args: -v -u
      env:
        - GO111MODULE=on
      cache:
        directories:
          - $GOPATH/pkg
          - $GOPATH/src
          - $GOROOT
      before_install:
        - go get -v github.com/golang/mock/mockgen
        - go install github.com/golang/mock/mockgen
        - go mod download
      script:
        - go test -coverprofile c.out ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - name: testnet
      language: go
      go:
        - 1.12.x
      go_import_path: github.com/Fantom-foundation/go-lachesis
      gobuild_args: -v -u
      cache:
        directories:
          - $GOPATH/pkg
          - $GOPATH/src
          - $GOROOT
      before_install:
        - go mod download
      script:
        - go test ./integration/
      env:
        - GO111MODULE=on
