matrix:
  allow_failures: java
  include:
    - name: go test
      language: go
      go:
        - 1.12.x
      go_import_path: github.com/Fantom-foundation/go-lachesis
      env:
        - GO111MODULE=off
      before_install:
        - go get -v github.com/SamuelMarks/batch-ethkey
        - go get -v github.com/golang/mock/mockgen
        - go install github.com/golang/mock/mockgen
        - go mod download
      addons:
        apt:
          packages:
            - jq
      script:
        - go test -coverprofile c.out ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - name: testnet
      language: go
      go:
        - 1.12.x
      go_import_path: github.com/Fantom-foundation/go-lachesis
      before_install:
        - go mod download
      addons:
        apt:
          packages:
            - jq
      script:
        - go test ./integration/
      env:
        - n=3
        - logshold='-1,-1,-1,5,0,0'
        - l_entry='main'
        - BUILD_DIR="$TRAVIS_BUILD_DIR"
        - GO111MODULE=off
#    - name: SonarQube automatic code reviewer
#      language: java
#      dist: trusty
#      addons:
#        sonarcloud:
#          organization: fantom-foundation
#      script:
#        - sonar-scanner
