// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frame.proto

package poset

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Frame struct {
	Round                int64           `protobuf:"varint,1,opt,name=Round,json=round,proto3" json:"Round,omitempty"`
	Roots                []*Root         `protobuf:"bytes,2,rep,name=Roots,json=roots,proto3" json:"Roots,omitempty"`
	Events               []*EventMessage `protobuf:"bytes,3,rep,name=Events,json=events,proto3" json:"Events,omitempty"`
	StateHash            []byte          `protobuf:"bytes,4,opt,name=StateHash,json=stateHash,proto3" json:"StateHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_5379e2b825e15002, []int{0}
}

func (m *Frame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frame.Unmarshal(m, b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
}
func (m *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(m, src)
}
func (m *Frame) XXX_Size() int {
	return xxx_messageInfo_Frame.Size(m)
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Frame) GetRoots() []*Root {
	if m != nil {
		return m.Roots
	}
	return nil
}

func (m *Frame) GetEvents() []*EventMessage {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *Frame) GetStateHash() []byte {
	if m != nil {
		return m.StateHash
	}
	return nil
}

func init() {
	proto.RegisterType((*Frame)(nil), "poset.Frame")
}

func init() { proto.RegisterFile("frame.proto", fileDescriptor_5379e2b825e15002) }

var fileDescriptor_5379e2b825e15002 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x86, 0x89, 0x35, 0x85, 0x26, 0x4e, 0xd1, 0x21, 0x14, 0x87, 0xea, 0x54, 0x10, 0x3a, 0xe8,
	0x33, 0x28, 0x2e, 0x2e, 0xf1, 0x09, 0x22, 0x9e, 0xba, 0xd8, 0x2b, 0xb9, 0xd3, 0x97, 0xf0, 0xa5,
	0xe5, 0x62, 0x1d, 0xff, 0x8f, 0x8f, 0xef, 0xce, 0xd8, 0x5b, 0x8a, 0x4f, 0xe8, 0x86, 0x84, 0x8c,
	0x4e, 0x0f, 0x48, 0xc0, 0xb5, 0x49, 0x88, 0xfc, 0x43, 0xb5, 0x85, 0x37, 0xf4, 0xe3, 0x58, 0x7f,
	0x94, 0xd1, 0x07, 0xf1, 0xdd, 0xc2, 0xe8, 0x80, 0xaf, 0xfe, 0xea, 0x55, 0xa3, 0xda, 0x22, 0xe8,
	0x24, 0xc3, 0xad, 0x84, 0x22, 0x93, 0x9f, 0x34, 0x45, 0x6b, 0xb7, 0xb6, 0xcb, 0xbd, 0x4e, 0x98,
	0x28, 0xc8, 0xe4, 0x36, 0xa6, 0xdc, 0x4b, 0x91, 0x7c, 0x91, 0x9d, 0xf9, 0xe8, 0x64, 0x78, 0x02,
	0xa2, 0x78, 0x87, 0x50, 0xe6, 0xa3, 0xe4, 0x96, 0xa6, 0x3a, 0x73, 0x64, 0x38, 0x46, 0x7a, 0xf8,
	0x69, 0xa3, 0xda, 0x59, 0xa8, 0xe8, 0x0f, 0x2e, 0x65, 0x7e, 0x6a, 0xf7, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0xcc, 0x98, 0x4a, 0xf9, 0xc3, 0x00, 0x00, 0x00,
}
