// Code generated by protoc-gen-go. DO NOT EDIT.
// source: roundInfo.proto

package poset

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Trilean int32

const (
	Trilean_UNDEFINED Trilean = 0
	Trilean_TRUE      Trilean = 1
	Trilean_FALSE     Trilean = 2
)

var Trilean_name = map[int32]string{
	0: "UNDEFINED",
	1: "TRUE",
	2: "FALSE",
}

var Trilean_value = map[string]int32{
	"UNDEFINED": 0,
	"TRUE":      1,
	"FALSE":     2,
}

func (x Trilean) String() string {
	return proto.EnumName(Trilean_name, int32(x))
}

func (Trilean) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_06add9379b5a2b9a, []int{0}
}

type RoundEvent struct {
	Consensus            bool     `protobuf:"varint,1,opt,name=Consensus,json=consensus,proto3" json:"Consensus,omitempty"`
	Clotho               bool     `protobuf:"varint,2,opt,name=Clotho,json=clotho,proto3" json:"Clotho,omitempty"`
	Atropos              Trilean  `protobuf:"varint,3,opt,name=Atropos,json=atropos,proto3,enum=poset.Trilean" json:"Atropos,omitempty"`
	RoundReceived        int64    `protobuf:"varint,4,opt,name=RoundReceived,json=roundReceived,proto3" json:"RoundReceived,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoundEvent) Reset()         { *m = RoundEvent{} }
func (m *RoundEvent) String() string { return proto.CompactTextString(m) }
func (*RoundEvent) ProtoMessage()    {}
func (*RoundEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_06add9379b5a2b9a, []int{0}
}

func (m *RoundEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoundEvent.Unmarshal(m, b)
}
func (m *RoundEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoundEvent.Marshal(b, m, deterministic)
}
func (m *RoundEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundEvent.Merge(m, src)
}
func (m *RoundEvent) XXX_Size() int {
	return xxx_messageInfo_RoundEvent.Size(m)
}
func (m *RoundEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RoundEvent proto.InternalMessageInfo

func (m *RoundEvent) GetConsensus() bool {
	if m != nil {
		return m.Consensus
	}
	return false
}

func (m *RoundEvent) GetClotho() bool {
	if m != nil {
		return m.Clotho
	}
	return false
}

func (m *RoundEvent) GetAtropos() Trilean {
	if m != nil {
		return m.Atropos
	}
	return Trilean_UNDEFINED
}

func (m *RoundEvent) GetRoundReceived() int64 {
	if m != nil {
		return m.RoundReceived
	}
	return 0
}

type RoundCreatedMessage struct {
	Events               map[string]*RoundEvent `protobuf:"bytes,1,rep,name=Events,json=events,proto3" json:"Events,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Queued               bool                   `protobuf:"varint,2,opt,name=queued,proto3" json:"queued,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RoundCreatedMessage) Reset()         { *m = RoundCreatedMessage{} }
func (m *RoundCreatedMessage) String() string { return proto.CompactTextString(m) }
func (*RoundCreatedMessage) ProtoMessage()    {}
func (*RoundCreatedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_06add9379b5a2b9a, []int{1}
}

func (m *RoundCreatedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoundCreatedMessage.Unmarshal(m, b)
}
func (m *RoundCreatedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoundCreatedMessage.Marshal(b, m, deterministic)
}
func (m *RoundCreatedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundCreatedMessage.Merge(m, src)
}
func (m *RoundCreatedMessage) XXX_Size() int {
	return xxx_messageInfo_RoundCreatedMessage.Size(m)
}
func (m *RoundCreatedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundCreatedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RoundCreatedMessage proto.InternalMessageInfo

func (m *RoundCreatedMessage) GetEvents() map[string]*RoundEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *RoundCreatedMessage) GetQueued() bool {
	if m != nil {
		return m.Queued
	}
	return false
}

type RoundReceived struct {
	Rounds               [][]byte `protobuf:"bytes,1,rep,name=Rounds,json=rounds,proto3" json:"Rounds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoundReceived) Reset()         { *m = RoundReceived{} }
func (m *RoundReceived) String() string { return proto.CompactTextString(m) }
func (*RoundReceived) ProtoMessage()    {}
func (*RoundReceived) Descriptor() ([]byte, []int) {
	return fileDescriptor_06add9379b5a2b9a, []int{2}
}

func (m *RoundReceived) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoundReceived.Unmarshal(m, b)
}
func (m *RoundReceived) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoundReceived.Marshal(b, m, deterministic)
}
func (m *RoundReceived) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundReceived.Merge(m, src)
}
func (m *RoundReceived) XXX_Size() int {
	return xxx_messageInfo_RoundReceived.Size(m)
}
func (m *RoundReceived) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundReceived.DiscardUnknown(m)
}

var xxx_messageInfo_RoundReceived proto.InternalMessageInfo

func (m *RoundReceived) GetRounds() [][]byte {
	if m != nil {
		return m.Rounds
	}
	return nil
}

func init() {
	proto.RegisterEnum("poset.Trilean", Trilean_name, Trilean_value)
	proto.RegisterType((*RoundEvent)(nil), "poset.RoundEvent")
	proto.RegisterType((*RoundCreatedMessage)(nil), "poset.RoundCreatedMessage")
	proto.RegisterMapType((map[string]*RoundEvent)(nil), "poset.RoundCreatedMessage.EventsEntry")
	proto.RegisterType((*RoundReceived)(nil), "poset.RoundReceived")
}

func init() { proto.RegisterFile("roundInfo.proto", fileDescriptor_06add9379b5a2b9a) }

var fileDescriptor_06add9379b5a2b9a = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x51, 0x4b, 0x32, 0x41,
	0x14, 0xfd, 0xc6, 0xd5, 0xd5, 0xbd, 0x7e, 0xda, 0x36, 0x41, 0x2c, 0xd1, 0x83, 0x48, 0xe4, 0x12,
	0xb4, 0x0f, 0xf6, 0x12, 0x3d, 0x04, 0xa2, 0x23, 0x08, 0xe6, 0xc3, 0xa4, 0x3f, 0x60, 0x73, 0x6f,
	0x25, 0xc9, 0x8c, 0xcd, 0xcc, 0x0a, 0xfe, 0x8d, 0xfe, 0x4e, 0x7f, 0x2e, 0xf6, 0xae, 0x82, 0x44,
	0x6f, 0x73, 0xcf, 0x39, 0x77, 0xce, 0x39, 0x33, 0x70, 0x62, 0x74, 0xae, 0xb2, 0x89, 0x7a, 0xd5,
	0xc9, 0xc6, 0x68, 0xa7, 0x79, 0x6d, 0xa3, 0x2d, 0xba, 0xee, 0x17, 0x03, 0x90, 0x05, 0x25, 0xb6,
	0xa8, 0x1c, 0xbf, 0x84, 0x60, 0xa8, 0x95, 0x45, 0x65, 0x73, 0x1b, 0xb1, 0x0e, 0x8b, 0x1b, 0x32,
	0x58, 0x1e, 0x00, 0x7e, 0x0e, 0xfe, 0x70, 0xad, 0xdd, 0xbb, 0x8e, 0x2a, 0x44, 0xf9, 0x4b, 0x9a,
	0x78, 0x0c, 0xf5, 0x81, 0x33, 0x7a, 0xa3, 0x6d, 0xe4, 0x75, 0x58, 0xdc, 0xee, 0xb7, 0x13, 0xba,
	0x3d, 0x99, 0x9b, 0xd5, 0x1a, 0x53, 0x25, 0xeb, 0x69, 0x49, 0xf3, 0x2b, 0x68, 0x91, 0x9b, 0xc4,
	0x25, 0xae, 0xb6, 0x98, 0x45, 0xd5, 0x0e, 0x8b, 0x3d, 0xd9, 0x32, 0xc7, 0x60, 0xf7, 0x9b, 0xc1,
	0x19, 0xc9, 0x86, 0x06, 0x53, 0x87, 0xd9, 0x13, 0x5a, 0x9b, 0xbe, 0x21, 0x7f, 0x04, 0x9f, 0x62,
	0x16, 0xd1, 0xbc, 0xb8, 0xd9, 0xbf, 0xde, 0xdb, 0xfc, 0xa1, 0x4d, 0x4a, 0xa1, 0x50, 0xce, 0xec,
	0xa4, 0x8f, 0x34, 0x14, 0xf9, 0x3f, 0x73, 0xcc, 0x31, 0x3b, 0xe4, 0x2f, 0xa7, 0x8b, 0x29, 0x34,
	0x8f, 0xe4, 0x3c, 0x04, 0xef, 0x03, 0x77, 0x54, 0x3f, 0x90, 0xc5, 0x91, 0xf7, 0xa0, 0xb6, 0x4d,
	0xd7, 0x39, 0xd2, 0x5e, 0xb3, 0x7f, 0x7a, 0xec, 0x4b, 0x9b, 0xb2, 0xe4, 0x1f, 0x2a, 0xf7, 0xac,
	0xdb, 0xfb, 0xd5, 0xb1, 0xb0, 0x25, 0xa0, 0x8c, 0xfd, 0x5f, 0xfa, 0xd4, 0xd6, 0xde, 0xdc, 0x42,
	0x7d, 0xff, 0x40, 0xbc, 0x05, 0xc1, 0x62, 0x36, 0x12, 0xe3, 0xc9, 0x4c, 0x8c, 0xc2, 0x7f, 0xbc,
	0x01, 0xd5, 0xb9, 0x5c, 0x88, 0x90, 0xf1, 0x00, 0x6a, 0xe3, 0xc1, 0xf4, 0x59, 0x84, 0x95, 0x17,
	0x9f, 0x3e, 0xee, 0xee, 0x27, 0x00, 0x00, 0xff, 0xff, 0xee, 0xb8, 0x0a, 0x7d, 0xcb, 0x01, 0x00,
	0x00,
}
