// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wire.proto

/*
Package wire is a generated protocol buffer package.

It is generated from these files:
	wire.proto

It has these top-level messages:
	InternalTransaction
	ExtTxns
	Event
	Block
*/
package wire

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InternalTransaction struct {
	Index      uint64 `protobuf:"varint,1,opt,name=Index" json:"Index,omitempty"`
	Amount     uint64 `protobuf:"varint,2,opt,name=Amount" json:"Amount,omitempty"`
	Receiver   string `protobuf:"bytes,3,opt,name=Receiver" json:"Receiver,omitempty"`
	UntilBlock uint64 `protobuf:"varint,4,opt,name=UntilBlock" json:"UntilBlock,omitempty"`
}

func (m *InternalTransaction) Reset()                    { *m = InternalTransaction{} }
func (m *InternalTransaction) String() string            { return proto.CompactTextString(m) }
func (*InternalTransaction) ProtoMessage()               {}
func (*InternalTransaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InternalTransaction) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *InternalTransaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *InternalTransaction) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *InternalTransaction) GetUntilBlock() uint64 {
	if m != nil {
		return m.UntilBlock
	}
	return 0
}

type ExtTxns struct {
	List [][]byte `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
}

func (m *ExtTxns) Reset()                    { *m = ExtTxns{} }
func (m *ExtTxns) String() string            { return proto.CompactTextString(m) }
func (*ExtTxns) ProtoMessage()               {}
func (*ExtTxns) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ExtTxns) GetList() [][]byte {
	if m != nil {
		return m.List
	}
	return nil
}

type Event struct {
	Index                uint64                 `protobuf:"varint,1,opt,name=Index" json:"Index,omitempty"`
	Creator              string                 `protobuf:"bytes,2,opt,name=Creator" json:"Creator,omitempty"`
	Parents              [][]byte               `protobuf:"bytes,3,rep,name=Parents,proto3" json:"Parents,omitempty"`
	LamportTime          uint64                 `protobuf:"varint,4,opt,name=LamportTime" json:"LamportTime,omitempty"`
	InternalTransactions []*InternalTransaction `protobuf:"bytes,5,rep,name=InternalTransactions" json:"InternalTransactions,omitempty"`
	// Types that are valid to be assigned to ExternalTransactions:
	//	*Event_ExtTxnsValue
	//	*Event_ExtTxnsHash
	ExternalTransactions isEvent_ExternalTransactions `protobuf_oneof:"ExternalTransactions"`
	Sign                 string                       `protobuf:"bytes,8,opt,name=Sign" json:"Sign,omitempty"`
	IsConfirmed          bool                         `protobuf:"varint,9,opt,name=IsConfirmed" json:"IsConfirmed,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isEvent_ExternalTransactions interface {
	isEvent_ExternalTransactions()
}

type Event_ExtTxnsValue struct {
	ExtTxnsValue *ExtTxns `protobuf:"bytes,6,opt,name=ExtTxnsValue,oneof"`
}
type Event_ExtTxnsHash struct {
	ExtTxnsHash []byte `protobuf:"bytes,7,opt,name=ExtTxnsHash,proto3,oneof"`
}

func (*Event_ExtTxnsValue) isEvent_ExternalTransactions() {}
func (*Event_ExtTxnsHash) isEvent_ExternalTransactions()  {}

func (m *Event) GetExternalTransactions() isEvent_ExternalTransactions {
	if m != nil {
		return m.ExternalTransactions
	}
	return nil
}

func (m *Event) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Event) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Event) GetParents() [][]byte {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *Event) GetLamportTime() uint64 {
	if m != nil {
		return m.LamportTime
	}
	return 0
}

func (m *Event) GetInternalTransactions() []*InternalTransaction {
	if m != nil {
		return m.InternalTransactions
	}
	return nil
}

func (m *Event) GetExtTxnsValue() *ExtTxns {
	if x, ok := m.GetExternalTransactions().(*Event_ExtTxnsValue); ok {
		return x.ExtTxnsValue
	}
	return nil
}

func (m *Event) GetExtTxnsHash() []byte {
	if x, ok := m.GetExternalTransactions().(*Event_ExtTxnsHash); ok {
		return x.ExtTxnsHash
	}
	return nil
}

func (m *Event) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *Event) GetIsConfirmed() bool {
	if m != nil {
		return m.IsConfirmed
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Event) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Event_OneofMarshaler, _Event_OneofUnmarshaler, _Event_OneofSizer, []interface{}{
		(*Event_ExtTxnsValue)(nil),
		(*Event_ExtTxnsHash)(nil),
	}
}

func _Event_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Event)
	// ExternalTransactions
	switch x := m.ExternalTransactions.(type) {
	case *Event_ExtTxnsValue:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExtTxnsValue); err != nil {
			return err
		}
	case *Event_ExtTxnsHash:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.ExtTxnsHash)
	case nil:
	default:
		return fmt.Errorf("Event.ExternalTransactions has unexpected type %T", x)
	}
	return nil
}

func _Event_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Event)
	switch tag {
	case 6: // ExternalTransactions.ExtTxnsValue
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExtTxns)
		err := b.DecodeMessage(msg)
		m.ExternalTransactions = &Event_ExtTxnsValue{msg}
		return true, err
	case 7: // ExternalTransactions.ExtTxnsHash
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.ExternalTransactions = &Event_ExtTxnsHash{x}
		return true, err
	default:
		return false, nil
	}
}

func _Event_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Event)
	// ExternalTransactions
	switch x := m.ExternalTransactions.(type) {
	case *Event_ExtTxnsValue:
		s := proto.Size(x.ExtTxnsValue)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Event_ExtTxnsHash:
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.ExtTxnsHash)))
		n += len(x.ExtTxnsHash)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Block struct {
	Index  uint64   `protobuf:"varint,1,opt,name=Index" json:"Index,omitempty"`
	Events [][]byte `protobuf:"bytes,2,rep,name=Events,proto3" json:"Events,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Block) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Block) GetEvents() [][]byte {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*InternalTransaction)(nil), "wire.InternalTransaction")
	proto.RegisterType((*ExtTxns)(nil), "wire.ExtTxns")
	proto.RegisterType((*Event)(nil), "wire.Event")
	proto.RegisterType((*Block)(nil), "wire.Block")
}

func init() { proto.RegisterFile("wire.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0xaf, 0xda, 0x30,
	0x10, 0x7c, 0x79, 0x49, 0xf8, 0xd8, 0xd0, 0x8b, 0x8b, 0x9e, 0xdc, 0x4a, 0xad, 0xa2, 0x9c, 0x72,
	0x81, 0x48, 0xa0, 0xaa, 0xea, 0xb1, 0x20, 0x2a, 0x90, 0xa8, 0x54, 0xb9, 0xb4, 0x87, 0xde, 0x4c,
	0x30, 0x60, 0x35, 0xb1, 0x91, 0xed, 0xd0, 0xdc, 0xfa, 0x7b, 0xfb, 0x2f, 0x2a, 0x9b, 0x50, 0xa5,
	0x7a, 0x70, 0xdb, 0x99, 0xf5, 0xae, 0x76, 0x66, 0x0c, 0xf0, 0x8b, 0x2b, 0x36, 0x3e, 0x29, 0x69,
	0x24, 0x0a, 0x6c, 0x9d, 0xfc, 0x86, 0x97, 0x2b, 0x61, 0x98, 0x12, 0xb4, 0xd8, 0x28, 0x2a, 0x34,
	0xcd, 0x0d, 0x97, 0x02, 0x0d, 0x21, 0x5c, 0x89, 0x1d, 0xab, 0xb1, 0x17, 0x7b, 0x69, 0x40, 0x2e,
	0x00, 0x3d, 0x41, 0xe7, 0x63, 0x29, 0x2b, 0x61, 0xf0, 0xa3, 0xa3, 0x1b, 0x84, 0x5e, 0x43, 0x8f,
	0xb0, 0x9c, 0xf1, 0x33, 0x53, 0xd8, 0x8f, 0xbd, 0xb4, 0x4f, 0xfe, 0x61, 0xf4, 0x16, 0xe0, 0x9b,
	0x30, 0xbc, 0x98, 0x15, 0x32, 0xff, 0x89, 0x03, 0x37, 0xd7, 0x62, 0x92, 0x37, 0xd0, 0x5d, 0xd4,
	0x66, 0x53, 0x0b, 0x8d, 0x10, 0x04, 0x6b, 0xae, 0xed, 0x72, 0x3f, 0x1d, 0x10, 0x57, 0x27, 0x7f,
	0x1e, 0x21, 0x5c, 0x9c, 0x99, 0x30, 0x77, 0x4e, 0xc2, 0xd0, 0x9d, 0x2b, 0x46, 0x8d, 0x54, 0xee,
	0xa6, 0x3e, 0xb9, 0x42, 0xdb, 0xf9, 0x42, 0x15, 0x13, 0x46, 0x63, 0xdf, 0x2d, 0xbc, 0x42, 0x14,
	0x43, 0xb4, 0xa6, 0xe5, 0x49, 0x2a, 0xb3, 0xe1, 0x25, 0x6b, 0x6e, 0x6a, 0x53, 0xe8, 0x33, 0x0c,
	0x6f, 0xb8, 0xa2, 0x71, 0x18, 0xfb, 0x69, 0x34, 0x79, 0x35, 0x76, 0x36, 0xde, 0x78, 0x41, 0x6e,
	0x8e, 0xa1, 0x29, 0x0c, 0x1a, 0x8d, 0xdf, 0x69, 0x51, 0x31, 0xdc, 0x89, 0xbd, 0x34, 0x9a, 0xbc,
	0xb8, 0xac, 0x69, 0x3a, 0xcb, 0x07, 0xf2, 0xdf, 0x23, 0x94, 0x40, 0x74, 0x6d, 0x51, 0x7d, 0xc4,
	0xdd, 0xd8, 0x4b, 0x07, 0xcb, 0x07, 0xd2, 0x26, 0xad, 0x63, 0x5f, 0xf9, 0x41, 0xe0, 0x9e, 0x93,
	0xee, 0x6a, 0xab, 0x6e, 0xa5, 0xe7, 0x52, 0xec, 0xb9, 0x2a, 0xd9, 0x0e, 0xf7, 0x63, 0x2f, 0xed,
	0x91, 0x36, 0x35, 0x7b, 0x82, 0xe1, 0xa2, 0x7e, 0x7e, 0x66, 0xf2, 0x0e, 0x42, 0x97, 0xc9, 0xfd,
	0xf4, 0x5d, 0x12, 0xba, 0x09, 0xa8, 0x41, 0xb3, 0x0f, 0x3f, 0xde, 0x1f, 0xb8, 0x39, 0x56, 0xdb,
	0x71, 0x2e, 0xcb, 0xec, 0x13, 0x15, 0x46, 0x96, 0xa3, 0xbd, 0xac, 0xc4, 0x8e, 0xda, 0xbd, 0xd9,
	0x41, 0x8e, 0x0a, 0x9a, 0x1f, 0x99, 0xe6, 0x3a, 0xd3, 0x2a, 0xcf, 0xb8, 0xb5, 0x28, 0xb3, 0xda,
	0xb7, 0x1d, 0xf7, 0x15, 0xa7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x5e, 0xff, 0x5d, 0x98,
	0x02, 0x00, 0x00,
}
