// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peer.proto

package peers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Peer struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	NetAddr              string   `protobuf:"bytes,2,opt,name=NetAddr,proto3" json:"NetAddr,omitempty"`
	PubKeyHex            string   `protobuf:"bytes,3,opt,name=PubKeyHex,proto3" json:"PubKeyHex,omitempty"`
	Used                 int64    `protobuf:"varint,4,opt,name=used,proto3" json:"used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peer) Reset()         { *m = Peer{} }
func (m *Peer) String() string { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()    {}
func (*Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{0}
}

func (m *Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peer.Unmarshal(m, b)
}
func (m *Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peer.Marshal(b, m, deterministic)
}
func (m *Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peer.Merge(m, src)
}
func (m *Peer) XXX_Size() int {
	return xxx_messageInfo_Peer.Size(m)
}
func (m *Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_Peer proto.InternalMessageInfo

func (m *Peer) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Peer) GetNetAddr() string {
	if m != nil {
		return m.NetAddr
	}
	return ""
}

func (m *Peer) GetPubKeyHex() string {
	if m != nil {
		return m.PubKeyHex
	}
	return ""
}

func (m *Peer) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

// PeerSet is a set of Peers forming a consensus network
type PeerSet struct {
	Peers    []*Peer          `protobuf:"bytes,1,rep,name=Peers,proto3" json:"Peers,omitempty"`
	ByPubKey map[string]*Peer `protobuf:"bytes,2,rep,name=ByPubKey,proto3" json:"ByPubKey,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ByID     map[uint32]*Peer `protobuf:"bytes,3,rep,name=ByID,proto3" json:"ByID,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// cached values
	Hash_                []byte   `protobuf:"bytes,4,opt,name=hash_,json=hash,proto3" json:"hash_,omitempty"`
	Hex_                 string   `protobuf:"bytes,5,opt,name=hex_,json=hex,proto3" json:"hex_,omitempty"`
	SuperMajority_       int64    `protobuf:"varint,6,opt,name=superMajority_,json=superMajority,proto3" json:"superMajority_,omitempty"`
	TrustCount_          int64    `protobuf:"varint,7,opt,name=trustCount_,json=trustCount,proto3" json:"trustCount_,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerSet) Reset()         { *m = PeerSet{} }
func (m *PeerSet) String() string { return proto.CompactTextString(m) }
func (*PeerSet) ProtoMessage()    {}
func (*PeerSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{1}
}

func (m *PeerSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerSet.Unmarshal(m, b)
}
func (m *PeerSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerSet.Marshal(b, m, deterministic)
}
func (m *PeerSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerSet.Merge(m, src)
}
func (m *PeerSet) XXX_Size() int {
	return xxx_messageInfo_PeerSet.Size(m)
}
func (m *PeerSet) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerSet.DiscardUnknown(m)
}

var xxx_messageInfo_PeerSet proto.InternalMessageInfo

func (m *PeerSet) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *PeerSet) GetByPubKey() map[string]*Peer {
	if m != nil {
		return m.ByPubKey
	}
	return nil
}

func (m *PeerSet) GetByID() map[uint32]*Peer {
	if m != nil {
		return m.ByID
	}
	return nil
}

func (m *PeerSet) GetHash_() []byte {
	if m != nil {
		return m.Hash_
	}
	return nil
}

func (m *PeerSet) GetHex_() string {
	if m != nil {
		return m.Hex_
	}
	return ""
}

func (m *PeerSet) GetSuperMajority_() int64 {
	if m != nil {
		return m.SuperMajority_
	}
	return 0
}

func (m *PeerSet) GetTrustCount_() int64 {
	if m != nil {
		return m.TrustCount_
	}
	return 0
}

func init() {
	proto.RegisterType((*Peer)(nil), "peers.Peer")
	proto.RegisterType((*PeerSet)(nil), "peers.PeerSet")
	proto.RegisterMapType((map[uint32]*Peer)(nil), "peers.PeerSet.ByIDEntry")
	proto.RegisterMapType((map[string]*Peer)(nil), "peers.PeerSet.ByPubKeyEntry")
}

func init() { proto.RegisterFile("peer.proto", fileDescriptor_055ae5a865fc1c9e) }

var fileDescriptor_055ae5a865fc1c9e = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0xd9, 0xa4, 0x35, 0x53, 0x53, 0x74, 0xbc, 0x2c, 0xa5, 0x60, 0x2c, 0x08, 0x39, 0x48,
	0x0e, 0x7a, 0x29, 0xde, 0xac, 0x11, 0x1a, 0x44, 0x29, 0xdb, 0x1f, 0x10, 0x5a, 0x3a, 0x10, 0x3f,
	0x68, 0xca, 0x66, 0x23, 0xcd, 0xff, 0xf0, 0x07, 0xcb, 0x4e, 0xe9, 0x97, 0x9e, 0xbc, 0xbd, 0x79,
	0xef, 0xcd, 0xec, 0xcc, 0x63, 0x01, 0x56, 0x44, 0x3a, 0x59, 0xe9, 0xd2, 0x94, 0xe8, 0x5b, 0x5c,
	0x0d, 0xe6, 0xe0, 0x4d, 0x88, 0x34, 0x76, 0xc1, 0xcd, 0x52, 0xe9, 0x44, 0x4e, 0x1c, 0x2a, 0x37,
	0x4b, 0x51, 0x42, 0xfb, 0x95, 0xcc, 0xc3, 0x62, 0xa1, 0xa5, 0x1b, 0x39, 0x71, 0xa0, 0xb6, 0x25,
	0xf6, 0x21, 0x98, 0xd4, 0xf3, 0x67, 0x6a, 0xc6, 0xb4, 0x96, 0x82, 0xb5, 0x3d, 0x81, 0x08, 0x5e,
	0x5d, 0xd1, 0x42, 0x7a, 0x91, 0x13, 0x0b, 0xc5, 0x78, 0xf0, 0x2d, 0xa0, 0x6d, 0x1f, 0x99, 0x92,
	0xc1, 0x2b, 0xf0, 0x2d, 0xac, 0xa4, 0x13, 0x89, 0xb8, 0x73, 0xdb, 0x49, 0x78, 0x8d, 0xc4, 0x72,
	0x6a, 0xa3, 0xe0, 0x10, 0x4e, 0x46, 0xcd, 0x66, 0xa2, 0x74, 0xd9, 0xd5, 0x3f, 0x70, 0x4d, 0xc9,
	0x24, 0x5b, 0xf9, 0x69, 0x69, 0x74, 0xa3, 0x76, 0x6e, 0xbc, 0x01, 0x6f, 0xd4, 0x64, 0xa9, 0x14,
	0xdc, 0x25, 0xff, 0x74, 0x65, 0xe9, 0xa6, 0x83, 0x5d, 0x78, 0x01, 0x7e, 0x31, 0xab, 0x8a, 0x9c,
	0x77, 0x3d, 0x55, 0x9e, 0x2d, 0xf0, 0x1c, 0xbc, 0x82, 0xd6, 0xb9, 0xf4, 0xf9, 0x30, 0x51, 0xd0,
	0x1a, 0xaf, 0xa1, 0x5b, 0xd5, 0x2b, 0xd2, 0x2f, 0xb3, 0xf7, 0x52, 0xbf, 0x99, 0x26, 0x97, 0x2d,
	0x3e, 0x2e, 0x3c, 0x62, 0xf1, 0x12, 0x3a, 0x46, 0xd7, 0x95, 0x79, 0x2c, 0xeb, 0xa5, 0xc9, 0x65,
	0x9b, 0x3d, 0xb0, 0xa7, 0x7a, 0x63, 0x08, 0x8f, 0x16, 0xc7, 0x33, 0x10, 0x1f, 0xd4, 0x70, 0xe8,
	0x81, 0xb2, 0xd0, 0xa6, 0xf3, 0x35, 0xfb, 0xac, 0x89, 0x33, 0xff, 0x9d, 0x0e, 0x2b, 0xf7, 0xee,
	0xd0, 0xe9, 0xa5, 0x10, 0xec, 0x8e, 0x39, 0x9c, 0x12, 0xfe, 0x67, 0xca, 0xbc, 0xc5, 0x1f, 0xe1,
	0xee, 0x27, 0x00, 0x00, 0xff, 0xff, 0x15, 0x0f, 0x58, 0xe7, 0x16, 0x02, 0x00, 0x00,
}
