// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peer.proto

package peers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Peer struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	NetAddr              string   `protobuf:"bytes,2,opt,name=NetAddr,proto3" json:"NetAddr,omitempty"`
	PubKeyHex            string   `protobuf:"bytes,3,opt,name=PubKeyHex,proto3" json:"PubKeyHex,omitempty"`
	Used                 int64    `protobuf:"varint,4,opt,name=used,proto3" json:"used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peer) Reset()         { *m = Peer{} }
func (m *Peer) String() string { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()    {}
func (*Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{0}
}

func (m *Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peer.Unmarshal(m, b)
}
func (m *Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peer.Marshal(b, m, deterministic)
}
func (m *Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peer.Merge(m, src)
}
func (m *Peer) XXX_Size() int {
	return xxx_messageInfo_Peer.Size(m)
}
func (m *Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_Peer proto.InternalMessageInfo

func (m *Peer) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Peer) GetNetAddr() string {
	if m != nil {
		return m.NetAddr
	}
	return ""
}

func (m *Peer) GetPubKeyHex() string {
	if m != nil {
		return m.PubKeyHex
	}
	return ""
}

func (m *Peer) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

type CachedValues struct {
	Hash                 []byte   `protobuf:"bytes,4,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Hex                  string   `protobuf:"bytes,5,opt,name=hex,proto3" json:"hex,omitempty"`
	SuperMajority        int64    `protobuf:"varint,6,opt,name=superMajority,proto3" json:"superMajority,omitempty"`
	TrustCount           int64    `protobuf:"varint,7,opt,name=trustCount,proto3" json:"trustCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CachedValues) Reset()         { *m = CachedValues{} }
func (m *CachedValues) String() string { return proto.CompactTextString(m) }
func (*CachedValues) ProtoMessage()    {}
func (*CachedValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{1}
}

func (m *CachedValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CachedValues.Unmarshal(m, b)
}
func (m *CachedValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CachedValues.Marshal(b, m, deterministic)
}
func (m *CachedValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CachedValues.Merge(m, src)
}
func (m *CachedValues) XXX_Size() int {
	return xxx_messageInfo_CachedValues.Size(m)
}
func (m *CachedValues) XXX_DiscardUnknown() {
	xxx_messageInfo_CachedValues.DiscardUnknown(m)
}

var xxx_messageInfo_CachedValues proto.InternalMessageInfo

func (m *CachedValues) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *CachedValues) GetHex() string {
	if m != nil {
		return m.Hex
	}
	return ""
}

func (m *CachedValues) GetSuperMajority() int64 {
	if m != nil {
		return m.SuperMajority
	}
	return 0
}

func (m *CachedValues) GetTrustCount() int64 {
	if m != nil {
		return m.TrustCount
	}
	return 0
}

// PeerSet is a set of Peers forming a consensus network
type PeerSet struct {
	Peers                []*Peer          `protobuf:"bytes,1,rep,name=Peers,proto3" json:"Peers,omitempty"`
	ByPubKey             map[string]*Peer `protobuf:"bytes,2,rep,name=ByPubKey,proto3" json:"ByPubKey,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ByID                 map[uint64]*Peer `protobuf:"bytes,3,rep,name=ByID,proto3" json:"ByID,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Cache                *CachedValues    `protobuf:"bytes,4,opt,name=cache,proto3" json:"cache,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PeerSet) Reset()         { *m = PeerSet{} }
func (m *PeerSet) String() string { return proto.CompactTextString(m) }
func (*PeerSet) ProtoMessage()    {}
func (*PeerSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{2}
}

func (m *PeerSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerSet.Unmarshal(m, b)
}
func (m *PeerSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerSet.Marshal(b, m, deterministic)
}
func (m *PeerSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerSet.Merge(m, src)
}
func (m *PeerSet) XXX_Size() int {
	return xxx_messageInfo_PeerSet.Size(m)
}
func (m *PeerSet) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerSet.DiscardUnknown(m)
}

var xxx_messageInfo_PeerSet proto.InternalMessageInfo

func (m *PeerSet) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *PeerSet) GetByPubKey() map[string]*Peer {
	if m != nil {
		return m.ByPubKey
	}
	return nil
}

func (m *PeerSet) GetByID() map[uint64]*Peer {
	if m != nil {
		return m.ByID
	}
	return nil
}

func (m *PeerSet) GetCache() *CachedValues {
	if m != nil {
		return m.Cache
	}
	return nil
}

func init() {
	proto.RegisterType((*Peer)(nil), "peers.Peer")
	proto.RegisterType((*CachedValues)(nil), "peers.CachedValues")
	proto.RegisterType((*PeerSet)(nil), "peers.PeerSet")
	proto.RegisterMapType((map[uint64]*Peer)(nil), "peers.PeerSet.ByIDEntry")
	proto.RegisterMapType((map[string]*Peer)(nil), "peers.PeerSet.ByPubKeyEntry")
}

func init() { proto.RegisterFile("peer.proto", fileDescriptor_055ae5a865fc1c9e) }

var fileDescriptor_055ae5a865fc1c9e = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xc9, 0xbf, 0xd6, 0x4c, 0x5b, 0x91, 0xf5, 0xb2, 0x94, 0x22, 0xb1, 0x78, 0x88, 0x20,
	0x39, 0xd4, 0x4b, 0xf1, 0x66, 0x1b, 0xa1, 0x41, 0x94, 0xb2, 0x05, 0xef, 0x69, 0x33, 0x50, 0xff,
	0xd0, 0x84, 0xdd, 0x8d, 0x34, 0x7e, 0x49, 0xbf, 0x92, 0xec, 0xc4, 0xd6, 0x54, 0x4f, 0xde, 0x5e,
	0x66, 0x7e, 0x33, 0xc9, 0x7b, 0x13, 0x80, 0x02, 0x51, 0x46, 0x85, 0xcc, 0x75, 0xce, 0x3c, 0xa3,
	0xd5, 0x70, 0x09, 0xee, 0x1c, 0x51, 0xb2, 0x63, 0xb0, 0x93, 0x98, 0x5b, 0x81, 0x15, 0xba, 0xc2,
	0x4e, 0x62, 0xc6, 0xa1, 0xfd, 0x88, 0xfa, 0x36, 0xcb, 0x24, 0xb7, 0x03, 0x2b, 0xf4, 0xc5, 0xee,
	0x91, 0x0d, 0xc0, 0x9f, 0x97, 0xcb, 0x7b, 0xac, 0x66, 0xb8, 0xe5, 0x0e, 0xf5, 0x7e, 0x0a, 0x8c,
	0x81, 0x5b, 0x2a, 0xcc, 0xb8, 0x1b, 0x58, 0xa1, 0x23, 0x48, 0x0f, 0x3f, 0xa0, 0x3b, 0x4d, 0x57,
	0x6b, 0xcc, 0x9e, 0xd2, 0xb7, 0x12, 0x95, 0x61, 0x66, 0xa9, 0x5a, 0x13, 0xd3, 0x15, 0xa4, 0xd9,
	0x09, 0x38, 0x6b, 0xdc, 0x72, 0x8f, 0xf6, 0x19, 0xc9, 0x2e, 0xa0, 0xa7, 0xca, 0x02, 0xe5, 0x43,
	0xfa, 0x92, 0xcb, 0x67, 0x5d, 0xf1, 0x16, 0xad, 0x3c, 0x2c, 0xb2, 0x33, 0x00, 0x2d, 0x4b, 0xa5,
	0xa7, 0x79, 0xb9, 0xd1, 0xbc, 0x4d, 0x48, 0xa3, 0x32, 0xfc, 0xb4, 0xa1, 0x6d, 0x0c, 0x2e, 0x50,
	0xb3, 0x73, 0xf0, 0x8c, 0x54, 0xdc, 0x0a, 0x9c, 0xb0, 0x33, 0xea, 0x44, 0x14, 0x41, 0x64, 0x6a,
	0xa2, 0xee, 0xb0, 0x31, 0x1c, 0x4d, 0xaa, 0xda, 0x0d, 0xb7, 0x89, 0x1a, 0x34, 0xa8, 0x05, 0xea,
	0x68, 0xd7, 0xbe, 0xdb, 0x68, 0x59, 0x89, 0x3d, 0xcd, 0xae, 0xc0, 0x9d, 0x54, 0x49, 0xcc, 0x1d,
	0x9a, 0xe2, 0x7f, 0xa6, 0x92, 0xb8, 0x9e, 0x20, 0x8a, 0x5d, 0x82, 0xb7, 0x32, 0x91, 0x50, 0x06,
	0x9d, 0xd1, 0xe9, 0x37, 0xde, 0x8c, 0x49, 0xd4, 0x44, 0x7f, 0x06, 0xbd, 0x83, 0x77, 0x9a, 0xa8,
	0x5e, 0xb1, 0xa2, 0x5b, 0xf9, 0xc2, 0x48, 0x63, 0xec, 0xdd, 0xcc, 0xd0, 0xa9, 0x7e, 0x1b, 0xa3,
	0xce, 0x8d, 0x3d, 0xb6, 0xfa, 0x31, 0xf8, 0xfb, 0xef, 0x68, 0x6e, 0x71, 0xff, 0xb3, 0x65, 0xd9,
	0xa2, 0xff, 0xe7, 0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x23, 0xb0, 0xfd, 0x3b, 0x4d, 0x02, 0x00,
	0x00,
}
