// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package poset

import (
	fmt "fmt"
	wire "github.com/Fantom-foundation/go-lachesis/src/inter/wire"
	peers "github.com/Fantom-foundation/go-lachesis/src/peers"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionType int32

const (
	TransactionType_PEER_ADD     TransactionType = 0
	TransactionType_PEER_REMOVE  TransactionType = 1
	TransactionType_POS_TRANSFER TransactionType = 2
)

var TransactionType_name = map[int32]string{
	0: "PEER_ADD",
	1: "PEER_REMOVE",
	2: "POS_TRANSFER",
}

var TransactionType_value = map[string]int32{
	"PEER_ADD":     0,
	"PEER_REMOVE":  1,
	"POS_TRANSFER": 2,
}

func (x TransactionType) String() string {
	return proto.EnumName(TransactionType_name, int32(x))
}

func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

type InternalTransaction struct {
	Type                 TransactionType    `protobuf:"varint,1,opt,name=Type,json=type,proto3,enum=poset.TransactionType" json:"Type,omitempty"`
	Peer                 *peers.PeerMessage `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	Amount               uint64             `protobuf:"varint,3,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *InternalTransaction) Reset()         { *m = InternalTransaction{} }
func (m *InternalTransaction) String() string { return proto.CompactTextString(m) }
func (*InternalTransaction) ProtoMessage()    {}
func (*InternalTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *InternalTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalTransaction.Unmarshal(m, b)
}
func (m *InternalTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalTransaction.Marshal(b, m, deterministic)
}
func (m *InternalTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalTransaction.Merge(m, src)
}
func (m *InternalTransaction) XXX_Size() int {
	return xxx_messageInfo_InternalTransaction.Size(m)
}
func (m *InternalTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_InternalTransaction proto.InternalMessageInfo

func (m *InternalTransaction) GetType() TransactionType {
	if m != nil {
		return m.Type
	}
	return TransactionType_PEER_ADD
}

func (m *InternalTransaction) GetPeer() *peers.PeerMessage {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *InternalTransaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type BlockSignature struct {
	Validator            []byte   `protobuf:"bytes,1,opt,name=Validator,json=validator,proto3" json:"Validator,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=Index,json=index,proto3" json:"Index,omitempty"`
	Signature            string   `protobuf:"bytes,3,opt,name=Signature,json=signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockSignature) Reset()         { *m = BlockSignature{} }
func (m *BlockSignature) String() string { return proto.CompactTextString(m) }
func (*BlockSignature) ProtoMessage()    {}
func (*BlockSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *BlockSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockSignature.Unmarshal(m, b)
}
func (m *BlockSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockSignature.Marshal(b, m, deterministic)
}
func (m *BlockSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockSignature.Merge(m, src)
}
func (m *BlockSignature) XXX_Size() int {
	return xxx_messageInfo_BlockSignature.Size(m)
}
func (m *BlockSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockSignature.DiscardUnknown(m)
}

var xxx_messageInfo_BlockSignature proto.InternalMessageInfo

func (m *BlockSignature) GetValidator() []byte {
	if m != nil {
		return m.Validator
	}
	return nil
}

func (m *BlockSignature) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *BlockSignature) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type EventBody struct {
	Transactions         [][]byte                    `protobuf:"bytes,1,rep,name=Transactions,json=transactions,proto3" json:"Transactions,omitempty"`
	InternalTransactions []*wire.InternalTransaction `protobuf:"bytes,2,rep,name=InternalTransactions,json=internalTransactions,proto3" json:"InternalTransactions,omitempty"`
	Parents              [][]byte                    `protobuf:"bytes,3,rep,name=Parents,json=parents,proto3" json:"Parents,omitempty"`
	Creator              []byte                      `protobuf:"bytes,4,opt,name=Creator,json=creator,proto3" json:"Creator,omitempty"`
	Index                int64                       `protobuf:"varint,5,opt,name=Index,json=index,proto3" json:"Index,omitempty"`
	BlockSignatures      []*BlockSignature           `protobuf:"bytes,6,rep,name=BlockSignatures,json=blockSignatures,proto3" json:"BlockSignatures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *EventBody) Reset()         { *m = EventBody{} }
func (m *EventBody) String() string { return proto.CompactTextString(m) }
func (*EventBody) ProtoMessage()    {}
func (*EventBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *EventBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventBody.Unmarshal(m, b)
}
func (m *EventBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventBody.Marshal(b, m, deterministic)
}
func (m *EventBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBody.Merge(m, src)
}
func (m *EventBody) XXX_Size() int {
	return xxx_messageInfo_EventBody.Size(m)
}
func (m *EventBody) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBody.DiscardUnknown(m)
}

var xxx_messageInfo_EventBody proto.InternalMessageInfo

func (m *EventBody) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *EventBody) GetInternalTransactions() []*wire.InternalTransaction {
	if m != nil {
		return m.InternalTransactions
	}
	return nil
}

func (m *EventBody) GetParents() [][]byte {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *EventBody) GetCreator() []byte {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *EventBody) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *EventBody) GetBlockSignatures() []*BlockSignature {
	if m != nil {
		return m.BlockSignatures
	}
	return nil
}

type EventMessage struct {
	Body                 *EventBody `protobuf:"bytes,1,opt,name=Body,json=body,proto3" json:"Body,omitempty"`
	Signature            string     `protobuf:"bytes,2,opt,name=Signature,json=signature,proto3" json:"Signature,omitempty"`
	SelfParentIndex      int64      `protobuf:"varint,3,opt,name=SelfParentIndex,json=selfParentIndex,proto3" json:"SelfParentIndex,omitempty"`
	OtherParentCreatorID uint64     `protobuf:"varint,4,opt,name=OtherParentCreatorID,json=otherParentCreatorID,proto3" json:"OtherParentCreatorID,omitempty"`
	OtherParentIndex     int64      `protobuf:"varint,5,opt,name=OtherParentIndex,json=otherParentIndex,proto3" json:"OtherParentIndex,omitempty"`
	CreatorID            uint64     `protobuf:"varint,6,opt,name=CreatorID,json=creatorID,proto3" json:"CreatorID,omitempty"`
	TopologicalIndex     int64      `protobuf:"varint,7,opt,name=TopologicalIndex,json=topologicalIndex,proto3" json:"TopologicalIndex,omitempty"`
	Hash                 []byte     `protobuf:"bytes,8,opt,name=Hash,json=hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EventMessage) Reset()         { *m = EventMessage{} }
func (m *EventMessage) String() string { return proto.CompactTextString(m) }
func (*EventMessage) ProtoMessage()    {}
func (*EventMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{3}
}

func (m *EventMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventMessage.Unmarshal(m, b)
}
func (m *EventMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventMessage.Marshal(b, m, deterministic)
}
func (m *EventMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMessage.Merge(m, src)
}
func (m *EventMessage) XXX_Size() int {
	return xxx_messageInfo_EventMessage.Size(m)
}
func (m *EventMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EventMessage proto.InternalMessageInfo

func (m *EventMessage) GetBody() *EventBody {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *EventMessage) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *EventMessage) GetSelfParentIndex() int64 {
	if m != nil {
		return m.SelfParentIndex
	}
	return 0
}

func (m *EventMessage) GetOtherParentCreatorID() uint64 {
	if m != nil {
		return m.OtherParentCreatorID
	}
	return 0
}

func (m *EventMessage) GetOtherParentIndex() int64 {
	if m != nil {
		return m.OtherParentIndex
	}
	return 0
}

func (m *EventMessage) GetCreatorID() uint64 {
	if m != nil {
		return m.CreatorID
	}
	return 0
}

func (m *EventMessage) GetTopologicalIndex() int64 {
	if m != nil {
		return m.TopologicalIndex
	}
	return 0
}

func (m *EventMessage) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Event struct {
	Message              *EventMessage `protobuf:"bytes,1,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
	LamportTimestamp     int64         `protobuf:"varint,2,opt,name=LamportTimestamp,json=lamportTimestamp,proto3" json:"LamportTimestamp,omitempty"`
	Frame                int64         `protobuf:"varint,3,opt,name=Frame,json=frame,proto3" json:"Frame,omitempty"`
	FlagTableBytes       []byte        `protobuf:"bytes,4,opt,name=FlagTableBytes,json=flagTableBytes,proto3" json:"FlagTableBytes,omitempty"`
	RootTableBytes       []byte        `protobuf:"bytes,5,opt,name=RootTableBytes,json=rootTableBytes,proto3" json:"RootTableBytes,omitempty"`
	Root                 bool          `protobuf:"varint,6,opt,name=Root,json=root,proto3" json:"Root,omitempty"`
	Clotho               bool          `protobuf:"varint,7,opt,name=Clotho,json=clotho,proto3" json:"Clotho,omitempty"`
	Atropos              bool          `protobuf:"varint,8,opt,name=Atropos,json=atropos,proto3" json:"Atropos,omitempty"`
	AtroposTimestamp     int64         `protobuf:"varint,9,opt,name=AtroposTimestamp,json=atroposTimestamp,proto3" json:"AtroposTimestamp,omitempty"`
	AtTimes              []int64       `protobuf:"varint,10,rep,packed,name=AtTimes,json=atTimes,proto3" json:"AtTimes,omitempty"`
	AtVisited            int64         `protobuf:"varint,11,opt,name=AtVisited,json=atVisited,proto3" json:"AtVisited,omitempty"`
	FrameReceived        int64         `protobuf:"varint,12,opt,name=FrameReceived,json=frameReceived,proto3" json:"FrameReceived,omitempty"`
	RecFrames            []int64       `protobuf:"varint,13,rep,packed,name=RecFrames,json=recFrames,proto3" json:"RecFrames,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{4}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetMessage() *EventMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Event) GetLamportTimestamp() int64 {
	if m != nil {
		return m.LamportTimestamp
	}
	return 0
}

func (m *Event) GetFrame() int64 {
	if m != nil {
		return m.Frame
	}
	return 0
}

func (m *Event) GetFlagTableBytes() []byte {
	if m != nil {
		return m.FlagTableBytes
	}
	return nil
}

func (m *Event) GetRootTableBytes() []byte {
	if m != nil {
		return m.RootTableBytes
	}
	return nil
}

func (m *Event) GetRoot() bool {
	if m != nil {
		return m.Root
	}
	return false
}

func (m *Event) GetClotho() bool {
	if m != nil {
		return m.Clotho
	}
	return false
}

func (m *Event) GetAtropos() bool {
	if m != nil {
		return m.Atropos
	}
	return false
}

func (m *Event) GetAtroposTimestamp() int64 {
	if m != nil {
		return m.AtroposTimestamp
	}
	return 0
}

func (m *Event) GetAtTimes() []int64 {
	if m != nil {
		return m.AtTimes
	}
	return nil
}

func (m *Event) GetAtVisited() int64 {
	if m != nil {
		return m.AtVisited
	}
	return 0
}

func (m *Event) GetFrameReceived() int64 {
	if m != nil {
		return m.FrameReceived
	}
	return 0
}

func (m *Event) GetRecFrames() []int64 {
	if m != nil {
		return m.RecFrames
	}
	return nil
}

func init() {
	proto.RegisterEnum("poset.TransactionType", TransactionType_name, TransactionType_value)
	proto.RegisterType((*InternalTransaction)(nil), "poset.InternalTransaction")
	proto.RegisterType((*BlockSignature)(nil), "poset.BlockSignature")
	proto.RegisterType((*EventBody)(nil), "poset.EventBody")
	proto.RegisterType((*EventMessage)(nil), "poset.EventMessage")
	proto.RegisterType((*Event)(nil), "poset.Event")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 738 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5f, 0x6f, 0xda, 0x3e,
	0x14, 0xfd, 0x41, 0xc2, 0x9f, 0x98, 0x14, 0x22, 0x97, 0x5f, 0x95, 0x55, 0x7b, 0x40, 0xa8, 0xaa,
	0x10, 0x52, 0x83, 0xc4, 0x9e, 0xa7, 0x09, 0x5a, 0xd0, 0x2a, 0xad, 0x2b, 0x32, 0xa8, 0xaf, 0x95,
	0x09, 0x06, 0xa2, 0x25, 0x71, 0x64, 0x9b, 0x6e, 0x3c, 0xee, 0x71, 0x5f, 0x68, 0x0f, 0xfb, 0x74,
	0x93, 0x6f, 0x42, 0x9b, 0x20, 0x5e, 0xf6, 0x82, 0x74, 0xce, 0xbd, 0x3e, 0xbe, 0xe7, 0x5c, 0x13,
	0xd4, 0x60, 0x2f, 0x2c, 0x56, 0x5e, 0x22, 0xb8, 0xe2, 0xb8, 0x92, 0x70, 0xc9, 0xd4, 0xe5, 0xed,
	0x26, 0x50, 0xdb, 0xdd, 0xd2, 0xf3, 0x79, 0x34, 0x98, 0xd2, 0x58, 0xf1, 0xe8, 0x66, 0xcd, 0x77,
	0xf1, 0x8a, 0xaa, 0x80, 0xc7, 0x83, 0x0d, 0xbf, 0x09, 0xa9, 0xbf, 0x65, 0x32, 0x90, 0x03, 0x29,
	0xfc, 0x41, 0x10, 0x2b, 0x26, 0x06, 0xdf, 0x03, 0xc1, 0x06, 0x39, 0xad, 0xcb, 0x8f, 0xff, 0x24,
	0x92, 0x30, 0x26, 0x24, 0xfc, 0xa6, 0xc7, 0xbb, 0x3f, 0x4b, 0xe8, 0xfc, 0x5e, 0x2b, 0xc7, 0x34,
	0x5c, 0x08, 0x1a, 0x4b, 0xea, 0xeb, 0x83, 0xb8, 0x8f, 0xcc, 0xc5, 0x3e, 0x61, 0x6e, 0xa9, 0x53,
	0xea, 0x35, 0x87, 0x17, 0x1e, 0x4c, 0xec, 0xe5, 0x3a, 0x74, 0x95, 0x98, 0x6a, 0x9f, 0x30, 0x7c,
	0x8d, 0x4c, 0xad, 0xe8, 0x96, 0x3b, 0xa5, 0x5e, 0x63, 0x88, 0x3d, 0xb8, 0xc4, 0x9b, 0x31, 0x26,
	0x1e, 0x98, 0x94, 0x74, 0xc3, 0x08, 0xd4, 0xf1, 0x05, 0xaa, 0x8e, 0x22, 0xbe, 0x8b, 0x95, 0x6b,
	0x74, 0x4a, 0x3d, 0x93, 0x54, 0x29, 0xa0, 0xee, 0x12, 0x35, 0xc7, 0x21, 0xf7, 0xbf, 0xcd, 0x83,
	0x4d, 0x4c, 0xd5, 0x4e, 0x30, 0xfc, 0x1e, 0x59, 0x4f, 0x34, 0x0c, 0x56, 0x54, 0x71, 0x01, 0x23,
	0xd8, 0xc4, 0x7a, 0x39, 0x10, 0xb8, 0x8d, 0x2a, 0xf7, 0xf1, 0x8a, 0xfd, 0x80, 0x0b, 0x0d, 0x52,
	0x09, 0x34, 0xd0, 0x67, 0x5e, 0x05, 0xe0, 0x02, 0x8b, 0x58, 0xf2, 0x40, 0x74, 0x7f, 0x95, 0x91,
	0x35, 0xd1, 0xb1, 0x8d, 0xf9, 0x6a, 0x8f, 0xbb, 0xc8, 0xce, 0x59, 0x91, 0x6e, 0xa9, 0x63, 0xf4,
	0x6c, 0x62, 0xab, 0x1c, 0x87, 0x1f, 0x50, 0xfb, 0x44, 0x30, 0xd2, 0x2d, 0x77, 0x8c, 0x5e, 0x63,
	0xf8, 0xce, 0xd3, 0x9b, 0xf0, 0x4e, 0x74, 0x90, 0x76, 0x70, 0xe2, 0x18, 0x76, 0x51, 0x6d, 0x46,
	0x05, 0x8b, 0x95, 0x74, 0x0d, 0xb8, 0xad, 0x96, 0xa4, 0x50, 0x57, 0x6e, 0x05, 0x03, 0xab, 0x26,
	0x58, 0xad, 0xf9, 0x29, 0x7c, 0x33, 0x5a, 0xc9, 0x1b, 0xfd, 0x84, 0x5a, 0xc5, 0xb8, 0xa4, 0x5b,
	0x85, 0x99, 0xfe, 0xcf, 0xb6, 0x54, 0xac, 0x92, 0xd6, 0xb2, 0xd8, 0xdd, 0xfd, 0x53, 0x46, 0x36,
	0x64, 0x91, 0xad, 0x07, 0x5f, 0x21, 0x53, 0xc7, 0x02, 0x49, 0x37, 0x86, 0x4e, 0x26, 0xf3, 0x1a,
	0x17, 0x31, 0x97, 0x3a, 0xb4, 0x42, 0xc0, 0xe5, 0xa3, 0x80, 0x71, 0x0f, 0xb5, 0xe6, 0x2c, 0x5c,
	0xa7, 0x1e, 0xd3, 0xa9, 0x0d, 0x98, 0xba, 0x25, 0x8b, 0x34, 0x1e, 0xa2, 0xf6, 0xa3, 0xda, 0x32,
	0x91, 0x72, 0x99, 0xf5, 0xfb, 0x3b, 0x30, 0x6f, 0x92, 0x36, 0x3f, 0x51, 0xc3, 0x7d, 0xe4, 0xe4,
	0xce, 0xe4, 0x43, 0x71, 0xf8, 0x11, 0xaf, 0xe7, 0x7c, 0x13, 0xad, 0x82, 0xa8, 0xe5, 0xe7, 0x95,
	0x16, 0x3c, 0xe1, 0x21, 0xdf, 0x04, 0x3e, 0x0d, 0x53, 0xa5, 0x5a, 0xaa, 0xa4, 0x8e, 0x78, 0x8c,
	0x91, 0xf9, 0x99, 0xca, 0xad, 0x5b, 0x87, 0xb5, 0x98, 0x5b, 0x2a, 0xb7, 0xdd, 0xdf, 0x06, 0xaa,
	0x40, 0x32, 0xf8, 0x06, 0xd5, 0xb2, 0x00, 0xb3, 0xe0, 0xce, 0xf3, 0xc1, 0x1d, 0x9e, 0x7e, 0x2d,
	0xca, 0x42, 0xee, 0x23, 0xe7, 0x0b, 0x8d, 0x12, 0x2e, 0xd4, 0x22, 0x88, 0x98, 0x54, 0x34, 0x4a,
	0xb2, 0x07, 0xec, 0x84, 0x47, 0xbc, 0x5e, 0xfc, 0x54, 0xd0, 0x88, 0x65, 0x11, 0x56, 0xd6, 0x1a,
	0xe0, 0x6b, 0xd4, 0x9c, 0x86, 0x74, 0xb3, 0xa0, 0xcb, 0x90, 0x8d, 0xf7, 0x8a, 0xc9, 0xec, 0xbd,
	0x34, 0xd7, 0x05, 0x56, 0xf7, 0x11, 0xce, 0x55, 0xae, 0xaf, 0x92, 0xf6, 0x89, 0x02, 0xab, 0xed,
	0xe9, 0x3e, 0xc8, 0xa8, 0x4e, 0x4c, 0x5d, 0xd5, 0xff, 0xd1, 0xdb, 0x90, 0xab, 0x2d, 0x87, 0x50,
	0xea, 0xa4, 0xea, 0x03, 0xd2, 0x8f, 0x74, 0xa4, 0x04, 0x4f, 0xb8, 0x84, 0x34, 0xea, 0xa4, 0x46,
	0x53, 0xa8, 0x7d, 0x65, 0x95, 0x37, 0x5f, 0x56, 0xea, 0x8b, 0x1e, 0xf1, 0xa9, 0x0a, 0x40, 0x17,
	0x75, 0x8c, 0x9e, 0xa1, 0x55, 0x00, 0xea, 0xa5, 0x8d, 0xd4, 0x53, 0x20, 0x03, 0xc5, 0x56, 0x6e,
	0x03, 0x8e, 0x5b, 0xf4, 0x40, 0xe0, 0x2b, 0x74, 0x06, 0x79, 0x10, 0xe6, 0xb3, 0xe0, 0x85, 0xad,
	0x5c, 0x1b, 0x3a, 0xce, 0xd6, 0x79, 0x52, 0x6b, 0x10, 0xe6, 0x43, 0xa3, 0x74, 0xcf, 0x40, 0xdf,
	0x12, 0x07, 0xa2, 0x3f, 0x46, 0xad, 0xa3, 0xcf, 0x17, 0xb6, 0x51, 0x7d, 0x36, 0x99, 0x90, 0xe7,
	0xd1, 0xdd, 0x9d, 0xf3, 0x1f, 0x6e, 0xa1, 0x06, 0x20, 0x32, 0x79, 0x78, 0x7c, 0x9a, 0x38, 0x25,
	0xec, 0x20, 0x7b, 0xf6, 0x38, 0x7f, 0x5e, 0x90, 0xd1, 0xd7, 0xf9, 0x74, 0x42, 0x9c, 0xf2, 0xb2,
	0x0a, 0x1f, 0xcd, 0x0f, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x6d, 0x00, 0x6c, 0xce, 0x05,
	0x00, 0x00,
}
