// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package poset

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import peers "github.com/Fantom-foundation/go-lachesis/src/peers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TransactionType int32

const (
	TransactionType_PEER_ADD     TransactionType = 0
	TransactionType_PEER_REMOVE  TransactionType = 1
	TransactionType_POS_TRANSFER TransactionType = 2
)

var TransactionType_name = map[int32]string{
	0: "PEER_ADD",
	1: "PEER_REMOVE",
	2: "POS_TRANSFER",
}
var TransactionType_value = map[string]int32{
	"PEER_ADD":     0,
	"PEER_REMOVE":  1,
	"POS_TRANSFER": 2,
}

func (x TransactionType) String() string {
	return proto.EnumName(TransactionType_name, int32(x))
}
func (TransactionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type InternalTransaction struct {
	Type   TransactionType    `protobuf:"varint,1,opt,name=Type,json=type,enum=poset.TransactionType" json:"Type,omitempty"`
	Peer   *peers.PeerMessage `protobuf:"bytes,2,opt,name=peer" json:"peer,omitempty"`
	Amount uint64             `protobuf:"varint,3,opt,name=Amount,json=amount" json:"Amount,omitempty"`
}

func (m *InternalTransaction) Reset()                    { *m = InternalTransaction{} }
func (m *InternalTransaction) String() string            { return proto.CompactTextString(m) }
func (*InternalTransaction) ProtoMessage()               {}
func (*InternalTransaction) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *InternalTransaction) GetType() TransactionType {
	if m != nil {
		return m.Type
	}
	return TransactionType_PEER_ADD
}

func (m *InternalTransaction) GetPeer() *peers.PeerMessage {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *InternalTransaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type BlockSignature struct {
	Validator []byte `protobuf:"bytes,1,opt,name=Validator,json=validator,proto3" json:"Validator,omitempty"`
	Index     int64  `protobuf:"varint,2,opt,name=Index,json=index" json:"Index,omitempty"`
	Signature string `protobuf:"bytes,3,opt,name=Signature,json=signature" json:"Signature,omitempty"`
}

func (m *BlockSignature) Reset()                    { *m = BlockSignature{} }
func (m *BlockSignature) String() string            { return proto.CompactTextString(m) }
func (*BlockSignature) ProtoMessage()               {}
func (*BlockSignature) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *BlockSignature) GetValidator() []byte {
	if m != nil {
		return m.Validator
	}
	return nil
}

func (m *BlockSignature) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *BlockSignature) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type EventBody struct {
	Transactions         [][]byte               `protobuf:"bytes,1,rep,name=Transactions,json=transactions,proto3" json:"Transactions,omitempty"`
	InternalTransactions []*InternalTransaction `protobuf:"bytes,2,rep,name=InternalTransactions,json=internalTransactions" json:"InternalTransactions,omitempty"`
	Parents              [][]byte               `protobuf:"bytes,3,rep,name=Parents,json=parents,proto3" json:"Parents,omitempty"`
	Creator              []byte                 `protobuf:"bytes,4,opt,name=Creator,json=creator,proto3" json:"Creator,omitempty"`
	Index                int64                  `protobuf:"varint,5,opt,name=Index,json=index" json:"Index,omitempty"`
	BlockSignatures      []*BlockSignature      `protobuf:"bytes,6,rep,name=BlockSignatures,json=blockSignatures" json:"BlockSignatures,omitempty"`
}

func (m *EventBody) Reset()                    { *m = EventBody{} }
func (m *EventBody) String() string            { return proto.CompactTextString(m) }
func (*EventBody) ProtoMessage()               {}
func (*EventBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *EventBody) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *EventBody) GetInternalTransactions() []*InternalTransaction {
	if m != nil {
		return m.InternalTransactions
	}
	return nil
}

func (m *EventBody) GetParents() [][]byte {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *EventBody) GetCreator() []byte {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *EventBody) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *EventBody) GetBlockSignatures() []*BlockSignature {
	if m != nil {
		return m.BlockSignatures
	}
	return nil
}

type EventMessage struct {
	Body                 *EventBody `protobuf:"bytes,1,opt,name=Body,json=body" json:"Body,omitempty"`
	Signature            string     `protobuf:"bytes,2,opt,name=Signature,json=signature" json:"Signature,omitempty"`
	SelfParentIndex      int64      `protobuf:"varint,3,opt,name=SelfParentIndex,json=selfParentIndex" json:"SelfParentIndex,omitempty"`
	OtherParentCreatorID uint64     `protobuf:"varint,4,opt,name=OtherParentCreatorID,json=otherParentCreatorID" json:"OtherParentCreatorID,omitempty"`
	OtherParentIndex     int64      `protobuf:"varint,5,opt,name=OtherParentIndex,json=otherParentIndex" json:"OtherParentIndex,omitempty"`
	CreatorID            uint64     `protobuf:"varint,6,opt,name=CreatorID,json=creatorID" json:"CreatorID,omitempty"`
	TopologicalIndex     int64      `protobuf:"varint,7,opt,name=TopologicalIndex,json=topologicalIndex" json:"TopologicalIndex,omitempty"`
	Hash                 []byte     `protobuf:"bytes,8,opt,name=Hash,json=hash,proto3" json:"Hash,omitempty"`
}

func (m *EventMessage) Reset()                    { *m = EventMessage{} }
func (m *EventMessage) String() string            { return proto.CompactTextString(m) }
func (*EventMessage) ProtoMessage()               {}
func (*EventMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *EventMessage) GetBody() *EventBody {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *EventMessage) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *EventMessage) GetSelfParentIndex() int64 {
	if m != nil {
		return m.SelfParentIndex
	}
	return 0
}

func (m *EventMessage) GetOtherParentCreatorID() uint64 {
	if m != nil {
		return m.OtherParentCreatorID
	}
	return 0
}

func (m *EventMessage) GetOtherParentIndex() int64 {
	if m != nil {
		return m.OtherParentIndex
	}
	return 0
}

func (m *EventMessage) GetCreatorID() uint64 {
	if m != nil {
		return m.CreatorID
	}
	return 0
}

func (m *EventMessage) GetTopologicalIndex() int64 {
	if m != nil {
		return m.TopologicalIndex
	}
	return 0
}

func (m *EventMessage) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Event struct {
	Message          *EventMessage `protobuf:"bytes,1,opt,name=Message,json=message" json:"Message,omitempty"`
	LamportTimestamp int64         `protobuf:"varint,2,opt,name=LamportTimestamp,json=lamportTimestamp" json:"LamportTimestamp,omitempty"`
	Frame            int64         `protobuf:"varint,3,opt,name=Frame,json=frame" json:"Frame,omitempty"`
	FlagTableBytes   []byte        `protobuf:"bytes,4,opt,name=FlagTableBytes,json=flagTableBytes,proto3" json:"FlagTableBytes,omitempty"`
	RootTableBytes   []byte        `protobuf:"bytes,5,opt,name=RootTableBytes,json=rootTableBytes,proto3" json:"RootTableBytes,omitempty"`
	Root             bool          `protobuf:"varint,6,opt,name=Root,json=root" json:"Root,omitempty"`
	Clotho           bool          `protobuf:"varint,7,opt,name=Clotho,json=clotho" json:"Clotho,omitempty"`
	Atropos          bool          `protobuf:"varint,8,opt,name=Atropos,json=atropos" json:"Atropos,omitempty"`
	AtroposTimestamp int64         `protobuf:"varint,9,opt,name=AtroposTimestamp,json=atroposTimestamp" json:"AtroposTimestamp,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Event) GetMessage() *EventMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Event) GetLamportTimestamp() int64 {
	if m != nil {
		return m.LamportTimestamp
	}
	return 0
}

func (m *Event) GetFrame() int64 {
	if m != nil {
		return m.Frame
	}
	return 0
}

func (m *Event) GetFlagTableBytes() []byte {
	if m != nil {
		return m.FlagTableBytes
	}
	return nil
}

func (m *Event) GetRootTableBytes() []byte {
	if m != nil {
		return m.RootTableBytes
	}
	return nil
}

func (m *Event) GetRoot() bool {
	if m != nil {
		return m.Root
	}
	return false
}

func (m *Event) GetClotho() bool {
	if m != nil {
		return m.Clotho
	}
	return false
}

func (m *Event) GetAtropos() bool {
	if m != nil {
		return m.Atropos
	}
	return false
}

func (m *Event) GetAtroposTimestamp() int64 {
	if m != nil {
		return m.AtroposTimestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*InternalTransaction)(nil), "poset.InternalTransaction")
	proto.RegisterType((*BlockSignature)(nil), "poset.BlockSignature")
	proto.RegisterType((*EventBody)(nil), "poset.EventBody")
	proto.RegisterType((*EventMessage)(nil), "poset.EventMessage")
	proto.RegisterType((*Event)(nil), "poset.Event")
	proto.RegisterEnum("poset.TransactionType", TransactionType_name, TransactionType_value)
}

func init() { proto.RegisterFile("event.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xd1, 0x6b, 0xe2, 0x4e,
	0x10, 0xc7, 0x7f, 0xd1, 0xc4, 0x98, 0x31, 0x68, 0xd8, 0xfa, 0x2b, 0xa1, 0xdc, 0x83, 0xc8, 0x51,
	0x44, 0xa8, 0x82, 0xf7, 0x7c, 0x1c, 0xda, 0x2a, 0x57, 0xb8, 0xb6, 0xb2, 0x4a, 0x5f, 0xcb, 0x1a,
	0x57, 0x13, 0x2e, 0xc9, 0x86, 0xdd, 0xb5, 0x9c, 0x8f, 0xf7, 0x7a, 0x7f, 0xd2, 0xfd, 0x75, 0xc7,
	0x6e, 0xd2, 0x36, 0x11, 0x5f, 0x84, 0xf9, 0xce, 0xec, 0xcc, 0x7c, 0x3f, 0xbb, 0x06, 0x5a, 0xf4,
	0x95, 0xa6, 0x72, 0x94, 0x71, 0x26, 0x19, 0xb2, 0x32, 0x26, 0xa8, 0xbc, 0xfa, 0xba, 0x8f, 0x64,
	0x78, 0xd8, 0x8c, 0x02, 0x96, 0x8c, 0x17, 0x24, 0x95, 0x2c, 0xb9, 0xd9, 0xb1, 0x43, 0xba, 0x25,
	0x32, 0x62, 0xe9, 0x78, 0xcf, 0x6e, 0x62, 0x12, 0x84, 0x54, 0x44, 0x62, 0x2c, 0x78, 0x30, 0xce,
	0x28, 0xe5, 0x42, 0xff, 0xe6, 0x5d, 0xfa, 0xbf, 0x0d, 0xb8, 0xb8, 0x4f, 0x25, 0xe5, 0x29, 0x89,
	0xd7, 0x9c, 0xa4, 0x82, 0x04, 0xea, 0x20, 0x1a, 0x82, 0xb9, 0x3e, 0x66, 0xd4, 0x37, 0x7a, 0xc6,
	0xa0, 0x3d, 0xb9, 0x1c, 0xe9, 0x61, 0xa3, 0x52, 0x85, 0xca, 0x62, 0x53, 0x1e, 0x33, 0x8a, 0xae,
	0xc1, 0x54, 0x1d, 0xfd, 0x5a, 0xcf, 0x18, 0xb4, 0x26, 0x68, 0xa4, 0x87, 0x8c, 0x96, 0x94, 0xf2,
	0x07, 0x2a, 0x04, 0xd9, 0x53, 0xac, 0xf3, 0xe8, 0x12, 0x1a, 0xd3, 0x84, 0x1d, 0x52, 0xe9, 0xd7,
	0x7b, 0xc6, 0xc0, 0xc4, 0x0d, 0xa2, 0xa3, 0xfe, 0x06, 0xda, 0xb3, 0x98, 0x05, 0x3f, 0x57, 0xd1,
	0x3e, 0x25, 0xf2, 0xc0, 0x29, 0xfa, 0x04, 0xce, 0x33, 0x89, 0xa3, 0x2d, 0x91, 0x8c, 0xeb, 0x15,
	0x5c, 0xec, 0xbc, 0xbe, 0x09, 0xa8, 0x0b, 0xd6, 0x7d, 0xba, 0xa5, 0xbf, 0xf4, 0xc0, 0x3a, 0xb6,
	0x22, 0x15, 0xa8, 0x33, 0xef, 0x0d, 0xf4, 0x00, 0x07, 0x3b, 0xe2, 0x4d, 0xe8, 0xff, 0xa9, 0x81,
	0x33, 0x57, 0xf4, 0x66, 0x6c, 0x7b, 0x44, 0x7d, 0x70, 0x4b, 0x56, 0x84, 0x6f, 0xf4, 0xea, 0x03,
	0x17, 0xbb, 0xb2, 0xa4, 0xa1, 0x47, 0xe8, 0x9e, 0x01, 0x23, 0xfc, 0x5a, 0xaf, 0x3e, 0x68, 0x4d,
	0xae, 0x0a, 0x22, 0x67, 0x4a, 0x70, 0x37, 0x3a, 0x73, 0x0e, 0xf9, 0x60, 0x2f, 0x09, 0xa7, 0xa9,
	0x14, 0x7e, 0x5d, 0x8f, 0xb3, 0xb3, 0x3c, 0x54, 0x99, 0x5b, 0x4e, 0xb5, 0x57, 0x53, 0x7b, 0xb5,
	0x83, 0x3c, 0xfc, 0x70, 0x6a, 0x95, 0x9d, 0x7e, 0x83, 0x4e, 0x95, 0x97, 0xf0, 0x1b, 0x7a, 0xa9,
	0xff, 0x8b, 0xa5, 0xaa, 0x59, 0xdc, 0xd9, 0x54, 0xab, 0xfb, 0x7f, 0x6b, 0xe0, 0x6a, 0x18, 0xc5,
	0xfd, 0xa0, 0xcf, 0x60, 0x2a, 0x2e, 0x1a, 0x75, 0x6b, 0xe2, 0x15, 0x6d, 0xde, 0x79, 0x61, 0x73,
	0xa3, 0xa8, 0x55, 0x08, 0xd7, 0x4e, 0x08, 0xa3, 0x01, 0x74, 0x56, 0x34, 0xde, 0xe5, 0x1e, 0xf3,
	0xad, 0xeb, 0x7a, 0xeb, 0x8e, 0xa8, 0xca, 0x68, 0x02, 0xdd, 0x27, 0x19, 0x52, 0x9e, 0x6b, 0x85,
	0xf5, 0xfb, 0x3b, 0x6d, 0xde, 0xc4, 0x5d, 0x76, 0x26, 0x87, 0x86, 0xe0, 0x95, 0xce, 0x94, 0xa1,
	0x78, 0xec, 0x44, 0x57, 0x7b, 0x7e, 0x34, 0x6d, 0xe8, 0xa6, 0x4e, 0x50, 0xee, 0xb4, 0x66, 0x19,
	0x8b, 0xd9, 0x3e, 0x0a, 0x48, 0x9c, 0x77, 0xb2, 0xf3, 0x4e, 0xf2, 0x44, 0x47, 0x08, 0xcc, 0xef,
	0x44, 0x84, 0x7e, 0x53, 0x5f, 0x8b, 0x19, 0x12, 0x11, 0x2a, 0x78, 0x96, 0x26, 0x83, 0x6e, 0xc0,
	0x2e, 0x00, 0x16, 0xe0, 0x2e, 0xca, 0xe0, 0xde, 0xde, 0xbe, 0x9d, 0x14, 0x90, 0x87, 0xe0, 0xfd,
	0x20, 0x49, 0xc6, 0xb8, 0x5c, 0x47, 0x09, 0x15, 0x92, 0x24, 0x59, 0xf1, 0x82, 0xbd, 0xf8, 0x44,
	0x57, 0x17, 0xbf, 0xe0, 0x24, 0xa1, 0x05, 0x42, 0x6b, 0xa7, 0x02, 0x74, 0x0d, 0xed, 0x45, 0x4c,
	0xf6, 0x6b, 0xb2, 0x89, 0xe9, 0xec, 0x28, 0xa9, 0x28, 0xde, 0x4b, 0x7b, 0x57, 0x51, 0x55, 0x1d,
	0x66, 0x4c, 0x96, 0xea, 0xac, 0xbc, 0x8e, 0x57, 0x54, 0x65, 0x4f, 0xd5, 0x69, 0x46, 0x4d, 0x6c,
	0xaa, 0xac, 0xfa, 0x93, 0xde, 0xc6, 0x4c, 0x86, 0x4c, 0x43, 0x69, 0xe2, 0x46, 0xa0, 0x23, 0xf5,
	0x48, 0xa7, 0x92, 0xb3, 0x8c, 0x09, 0x4d, 0xa3, 0x89, 0x6d, 0x92, 0x87, 0xca, 0x57, 0x91, 0xf9,
	0xf0, 0xe5, 0xe4, 0xbe, 0xc8, 0x89, 0x3e, 0x9c, 0x41, 0xe7, 0xe4, 0x1b, 0x82, 0x5c, 0x68, 0x2e,
	0xe7, 0x73, 0xfc, 0x32, 0xbd, 0xbb, 0xf3, 0xfe, 0x43, 0x1d, 0x68, 0xe9, 0x08, 0xcf, 0x1f, 0x9e,
	0x9e, 0xe7, 0x9e, 0x81, 0x3c, 0x70, 0x97, 0x4f, 0xab, 0x97, 0x35, 0x9e, 0x3e, 0xae, 0x16, 0x73,
	0xec, 0xd5, 0x36, 0x0d, 0xfd, 0xe5, 0xfa, 0xf2, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x8b, 0xc7,
	0x83, 0x0e, 0x05, 0x00, 0x00,
}
