// Code generated by protoc-gen-go. DO NOT EDIT.
// source: root.proto

package poset

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RootEvent struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	CreatorID            uint64   `protobuf:"varint,2,opt,name=CreatorID,proto3" json:"CreatorID,omitempty"`
	Index                int64    `protobuf:"varint,3,opt,name=Index,proto3" json:"Index,omitempty"`
	LamportTimestamp     int64    `protobuf:"varint,4,opt,name=LamportTimestamp,proto3" json:"LamportTimestamp,omitempty"`
	Round                int64    `protobuf:"varint,5,opt,name=Round,proto3" json:"Round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RootEvent) Reset()         { *m = RootEvent{} }
func (m *RootEvent) String() string { return proto.CompactTextString(m) }
func (*RootEvent) ProtoMessage()    {}
func (*RootEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_55f7b5715fe1bcd1, []int{0}
}
func (m *RootEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RootEvent.Unmarshal(m, b)
}
func (m *RootEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RootEvent.Marshal(b, m, deterministic)
}
func (dst *RootEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RootEvent.Merge(dst, src)
}
func (m *RootEvent) XXX_Size() int {
	return xxx_messageInfo_RootEvent.Size(m)
}
func (m *RootEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RootEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RootEvent proto.InternalMessageInfo

func (m *RootEvent) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *RootEvent) GetCreatorID() uint64 {
	if m != nil {
		return m.CreatorID
	}
	return 0
}

func (m *RootEvent) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *RootEvent) GetLamportTimestamp() int64 {
	if m != nil {
		return m.LamportTimestamp
	}
	return 0
}

func (m *RootEvent) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type RootEvents struct {
	Value                []*RootEvent `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RootEvents) Reset()         { *m = RootEvents{} }
func (m *RootEvents) String() string { return proto.CompactTextString(m) }
func (*RootEvents) ProtoMessage()    {}
func (*RootEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_55f7b5715fe1bcd1, []int{1}
}
func (m *RootEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RootEvents.Unmarshal(m, b)
}
func (m *RootEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RootEvents.Marshal(b, m, deterministic)
}
func (dst *RootEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RootEvents.Merge(dst, src)
}
func (m *RootEvents) XXX_Size() int {
	return xxx_messageInfo_RootEvents.Size(m)
}
func (m *RootEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_RootEvents.DiscardUnknown(m)
}

var xxx_messageInfo_RootEvents proto.InternalMessageInfo

func (m *RootEvents) GetValue() []*RootEvent {
	if m != nil {
		return m.Value
	}
	return nil
}

type Root struct {
	NextRound            int64                  `protobuf:"varint,1,opt,name=NextRound,proto3" json:"NextRound,omitempty"`
	SelfParent           *RootEvent             `protobuf:"bytes,2,opt,name=SelfParent,proto3" json:"SelfParent,omitempty"`
	Others               map[string]*RootEvents `protobuf:"bytes,3,rep,name=Others,proto3" json:"Others,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Root) Reset()         { *m = Root{} }
func (m *Root) String() string { return proto.CompactTextString(m) }
func (*Root) ProtoMessage()    {}
func (*Root) Descriptor() ([]byte, []int) {
	return fileDescriptor_root_55f7b5715fe1bcd1, []int{2}
}
func (m *Root) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Root.Unmarshal(m, b)
}
func (m *Root) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Root.Marshal(b, m, deterministic)
}
func (dst *Root) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Root.Merge(dst, src)
}
func (m *Root) XXX_Size() int {
	return xxx_messageInfo_Root.Size(m)
}
func (m *Root) XXX_DiscardUnknown() {
	xxx_messageInfo_Root.DiscardUnknown(m)
}

var xxx_messageInfo_Root proto.InternalMessageInfo

func (m *Root) GetNextRound() int64 {
	if m != nil {
		return m.NextRound
	}
	return 0
}

func (m *Root) GetSelfParent() *RootEvent {
	if m != nil {
		return m.SelfParent
	}
	return nil
}

func (m *Root) GetOthers() map[string]*RootEvents {
	if m != nil {
		return m.Others
	}
	return nil
}

func init() {
	proto.RegisterType((*RootEvent)(nil), "poset.RootEvent")
	proto.RegisterType((*RootEvents)(nil), "poset.RootEvents")
	proto.RegisterType((*Root)(nil), "poset.Root")
	proto.RegisterMapType((map[string]*RootEvents)(nil), "poset.Root.OthersEntry")
}

func init() { proto.RegisterFile("root.proto", fileDescriptor_root_55f7b5715fe1bcd1) }

var fileDescriptor_root_55f7b5715fe1bcd1 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0x26, 0x29, 0x74, 0xea, 0x21, 0x0e, 0x82, 0x8b, 0x78, 0x08, 0x39, 0x68, 0xf0,
	0x10, 0x45, 0x3d, 0x88, 0x57, 0x2d, 0x58, 0x28, 0x2a, 0xab, 0x78, 0x5f, 0xe9, 0x48, 0xc5, 0x26,
	0x1b, 0x76, 0xa7, 0xa5, 0xfd, 0x21, 0xfe, 0x34, 0xff, 0x8f, 0x64, 0x57, 0xda, 0xa0, 0xde, 0x76,
	0xde, 0x7b, 0xbc, 0xf9, 0x86, 0x05, 0xb0, 0xc6, 0x70, 0xd9, 0x58, 0xc3, 0x06, 0x93, 0xc6, 0x38,
	0xe2, 0xfc, 0x53, 0xc0, 0x40, 0x19, 0xc3, 0xa3, 0x25, 0xd5, 0x8c, 0x08, 0xf1, 0x9d, 0x76, 0x33,
	0x29, 0x32, 0x51, 0xec, 0x28, 0xff, 0xc6, 0x43, 0x18, 0xdc, 0x58, 0xd2, 0x6c, 0xec, 0xf8, 0x56,
	0xf6, 0x32, 0x51, 0xc4, 0x6a, 0x2b, 0xe0, 0x1e, 0x24, 0xe3, 0x7a, 0x4a, 0x2b, 0x19, 0x65, 0xa2,
	0x88, 0x54, 0x18, 0xf0, 0x04, 0xd2, 0x89, 0xae, 0x1a, 0x63, 0xf9, 0xf9, 0xbd, 0x22, 0xc7, 0xba,
	0x6a, 0x64, 0xec, 0x03, 0x7f, 0xf4, 0xb6, 0x41, 0x99, 0x45, 0x3d, 0x95, 0x49, 0x68, 0xf0, 0x43,
	0x7e, 0x09, 0xb0, 0xc1, 0x72, 0x78, 0x04, 0xc9, 0x8b, 0x9e, 0x2f, 0x48, 0x8a, 0x2c, 0x2a, 0x86,
	0xe7, 0x69, 0xe9, 0xe1, 0xcb, 0x4d, 0x42, 0x05, 0x3b, 0xff, 0x12, 0x10, 0xb7, 0x62, 0x0b, 0x7d,
	0x4f, 0x2b, 0x0e, 0xc5, 0xc2, 0x17, 0x6f, 0x05, 0x3c, 0x03, 0x78, 0xa2, 0xf9, 0xdb, 0xa3, 0xb6,
	0x54, 0xb3, 0xbf, 0xe9, 0xbf, 0xce, 0x4e, 0x06, 0x4f, 0xa1, 0xff, 0xc0, 0x33, 0xb2, 0x4e, 0x46,
	0x9e, 0x60, 0xbf, 0x93, 0x2e, 0x83, 0x33, 0xaa, 0xd9, 0xae, 0xd5, 0x4f, 0xec, 0x60, 0x02, 0xc3,
	0x8e, 0x8c, 0x29, 0x44, 0x1f, 0xb4, 0xf6, 0x24, 0x03, 0xd5, 0x3e, 0xf1, 0x18, 0x92, 0xa5, 0x3f,
	0x29, 0xac, 0xdf, 0xfd, 0xbd, 0xde, 0xa9, 0xe0, 0x5f, 0xf7, 0xae, 0xc4, 0x6b, 0xdf, 0xff, 0xd9,
	0xc5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x84, 0xb1, 0xbe, 0xc1, 0x01, 0x00, 0x00,
}
