// Code generated by protoc-gen-go. DO NOT EDIT.
// source: root.proto

package poset

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RootEvent struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	CreatorID            uint32   `protobuf:"varint,2,opt,name=CreatorID,proto3" json:"CreatorID,omitempty"`
	Index                int64    `protobuf:"varint,3,opt,name=Index,proto3" json:"Index,omitempty"`
	LamportTimestamp     int64    `protobuf:"varint,4,opt,name=LamportTimestamp,proto3" json:"LamportTimestamp,omitempty"`
	Round                int64    `protobuf:"varint,5,opt,name=Round,proto3" json:"Round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RootEvent) Reset()         { *m = RootEvent{} }
func (m *RootEvent) String() string { return proto.CompactTextString(m) }
func (*RootEvent) ProtoMessage()    {}
func (*RootEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_08a043f6ee9336a8, []int{0}
}

func (m *RootEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RootEvent.Unmarshal(m, b)
}
func (m *RootEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RootEvent.Marshal(b, m, deterministic)
}
func (m *RootEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RootEvent.Merge(m, src)
}
func (m *RootEvent) XXX_Size() int {
	return xxx_messageInfo_RootEvent.Size(m)
}
func (m *RootEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RootEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RootEvent proto.InternalMessageInfo

func (m *RootEvent) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *RootEvent) GetCreatorID() uint32 {
	if m != nil {
		return m.CreatorID
	}
	return 0
}

func (m *RootEvent) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *RootEvent) GetLamportTimestamp() int64 {
	if m != nil {
		return m.LamportTimestamp
	}
	return 0
}

func (m *RootEvent) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type Root struct {
	NextRound            int64                 `protobuf:"varint,1,opt,name=NextRound,proto3" json:"NextRound,omitempty"`
	SelfParent           *RootEvent            `protobuf:"bytes,2,opt,name=SelfParent,proto3" json:"SelfParent,omitempty"`
	Others               map[string]*RootEvent `protobuf:"bytes,3,rep,name=Others,proto3" json:"Others,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Root) Reset()         { *m = Root{} }
func (m *Root) String() string { return proto.CompactTextString(m) }
func (*Root) ProtoMessage()    {}
func (*Root) Descriptor() ([]byte, []int) {
	return fileDescriptor_08a043f6ee9336a8, []int{1}
}

func (m *Root) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Root.Unmarshal(m, b)
}
func (m *Root) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Root.Marshal(b, m, deterministic)
}
func (m *Root) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Root.Merge(m, src)
}
func (m *Root) XXX_Size() int {
	return xxx_messageInfo_Root.Size(m)
}
func (m *Root) XXX_DiscardUnknown() {
	xxx_messageInfo_Root.DiscardUnknown(m)
}

var xxx_messageInfo_Root proto.InternalMessageInfo

func (m *Root) GetNextRound() int64 {
	if m != nil {
		return m.NextRound
	}
	return 0
}

func (m *Root) GetSelfParent() *RootEvent {
	if m != nil {
		return m.SelfParent
	}
	return nil
}

func (m *Root) GetOthers() map[string]*RootEvent {
	if m != nil {
		return m.Others
	}
	return nil
}

func init() {
	proto.RegisterType((*RootEvent)(nil), "poset.RootEvent")
	proto.RegisterType((*Root)(nil), "poset.Root")
	proto.RegisterMapType((map[string]*RootEvent)(nil), "poset.Root.OthersEntry")
}

func init() { proto.RegisterFile("root.proto", fileDescriptor_08a043f6ee9336a8) }

var fileDescriptor_08a043f6ee9336a8 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x80, 0xd9, 0xa6, 0x29, 0x64, 0x82, 0x10, 0x06, 0xc1, 0x45, 0x3c, 0x84, 0x1e, 0x24, 0x78,
	0x88, 0x52, 0x2f, 0xe2, 0x55, 0x0b, 0x16, 0x45, 0x65, 0xf5, 0x05, 0x56, 0x3a, 0x52, 0xb1, 0xc9,
	0x84, 0xcd, 0xb4, 0xb4, 0x0f, 0xe2, 0x9b, 0xf9, 0x40, 0x92, 0xdd, 0x62, 0x03, 0xe2, 0x6d, 0xe6,
	0x9b, 0x8f, 0xf9, 0x03, 0x70, 0xcc, 0x52, 0x36, 0x8e, 0x85, 0x31, 0x6e, 0xb8, 0x25, 0x19, 0x7f,
	0x29, 0x48, 0x0c, 0xb3, 0x4c, 0xd7, 0x54, 0x0b, 0x22, 0x0c, 0xef, 0x6c, 0xbb, 0xd0, 0x2a, 0x57,
	0x45, 0x62, 0x7c, 0x8c, 0x27, 0x90, 0xdc, 0x38, 0xb2, 0xc2, 0x6e, 0x76, 0xab, 0x07, 0xb9, 0x2a,
	0x0e, 0xcc, 0x1e, 0xe0, 0x21, 0xc4, 0xb3, 0x7a, 0x4e, 0x1b, 0x1d, 0xe5, 0xaa, 0x88, 0x4c, 0x48,
	0xf0, 0x0c, 0xb2, 0x07, 0x5b, 0x35, 0xec, 0xe4, 0xf5, 0xa3, 0xa2, 0x56, 0x6c, 0xd5, 0xe8, 0xa1,
	0x17, 0xfe, 0xf0, 0xae, 0x83, 0xe1, 0x55, 0x3d, 0xd7, 0x71, 0xe8, 0xe0, 0x93, 0xf1, 0xb7, 0x82,
	0x61, 0xb7, 0x57, 0x37, 0xfe, 0x91, 0x36, 0x12, 0x14, 0xe5, 0x95, 0x3d, 0xc0, 0x0b, 0x80, 0x17,
	0x5a, 0xbe, 0x3f, 0x5b, 0x47, 0xb5, 0xf8, 0xed, 0xd2, 0x49, 0x56, 0xfa, 0xd3, 0xca, 0xdf, 0xb3,
	0x4c, 0xcf, 0xc1, 0x73, 0x18, 0x3d, 0xc9, 0x82, 0x5c, 0xab, 0xa3, 0x3c, 0x2a, 0xd2, 0xc9, 0x51,
	0xcf, 0x2e, 0x43, 0x65, 0x5a, 0x8b, 0xdb, 0x9a, 0x9d, 0x76, 0x7c, 0x0f, 0x69, 0x0f, 0x63, 0x06,
	0xd1, 0x27, 0x6d, 0x77, 0x1f, 0xea, 0x42, 0x3c, 0x85, 0x78, 0x6d, 0x97, 0x2b, 0xfa, 0x77, 0x7c,
	0x28, 0x5f, 0x0f, 0xae, 0xd4, 0xdb, 0xc8, 0x3f, 0xff, 0xf2, 0x27, 0x00, 0x00, 0xff, 0xff, 0x8d,
	0x32, 0xc9, 0x07, 0x8a, 0x01, 0x00, 0x00,
}
